// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: task/task.proto

package hellowrold

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TaskserviceClient is the client API for Taskservice service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TaskserviceClient interface {
	AddTask(ctx context.Context, in *Task, opts ...grpc.CallOption) (*TaskResponse, error)
	GetTask(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TaskList, error)
}

type taskserviceClient struct {
	cc grpc.ClientConnInterface
}

func NewTaskserviceClient(cc grpc.ClientConnInterface) TaskserviceClient {
	return &taskserviceClient{cc}
}

func (c *taskserviceClient) AddTask(ctx context.Context, in *Task, opts ...grpc.CallOption) (*TaskResponse, error) {
	out := new(TaskResponse)
	err := c.cc.Invoke(ctx, "/task.Taskservice/AddTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskserviceClient) GetTask(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TaskList, error) {
	out := new(TaskList)
	err := c.cc.Invoke(ctx, "/task.Taskservice/GetTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaskserviceServer is the server API for Taskservice service.
// All implementations must embed UnimplementedTaskserviceServer
// for forward compatibility
type TaskserviceServer interface {
	AddTask(context.Context, *Task) (*TaskResponse, error)
	GetTask(context.Context, *Empty) (*TaskList, error)
	mustEmbedUnimplementedTaskserviceServer()
}

// UnimplementedTaskserviceServer must be embedded to have forward compatible implementations.
type UnimplementedTaskserviceServer struct {
}

func (UnimplementedTaskserviceServer) AddTask(context.Context, *Task) (*TaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddTask not implemented")
}
func (UnimplementedTaskserviceServer) GetTask(context.Context, *Empty) (*TaskList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTask not implemented")
}
func (UnimplementedTaskserviceServer) mustEmbedUnimplementedTaskserviceServer() {}

// UnsafeTaskserviceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TaskserviceServer will
// result in compilation errors.
type UnsafeTaskserviceServer interface {
	mustEmbedUnimplementedTaskserviceServer()
}

func RegisterTaskserviceServer(s grpc.ServiceRegistrar, srv TaskserviceServer) {
	s.RegisterService(&Taskservice_ServiceDesc, srv)
}

func _Taskservice_AddTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Task)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskserviceServer).AddTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/task.Taskservice/AddTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskserviceServer).AddTask(ctx, req.(*Task))
	}
	return interceptor(ctx, in, info, handler)
}

func _Taskservice_GetTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskserviceServer).GetTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/task.Taskservice/GetTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskserviceServer).GetTask(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Taskservice_ServiceDesc is the grpc.ServiceDesc for Taskservice service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Taskservice_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "task.Taskservice",
	HandlerType: (*TaskserviceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddTask",
			Handler:    _Taskservice_AddTask_Handler,
		},
		{
			MethodName: "GetTask",
			Handler:    _Taskservice_GetTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "task/task.proto",
}
